# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6013c5f1d4f58a7794a4bb15f1bc07fd7a3748106cd140183dcbfb4491f90c187233a26c3aecd612329e638c02600e61d4da1e2d834b3df32c99d61d90c3b9f

test:
  secret_key_base: 49da00516098e31ce00c257a74f5e700b2da7bc735c856f5261ebf7f929247c30d3321fbd82a5dfb95b43aa6efc3110f13c7545000b28ad7f5cefa6e0acaca54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
